config/routes.rb
Rails.application.routes.draw do
  resources :contacts do
    resources :events
  end
  resources :events, only: [:index]

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#splash'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/has_image.rb
module HasImage
  extend ActiveSupport::Concern

  included do
    has_one_attached :image
    validate :acceptable_image?
  end

  def displayed_image
    if image.attached?
      image
    else
      "profile-default.png"
    end
  end

  private

  def acceptable_image?
    return unless image.attached?
    acceptable_image_size?
    acceptable_image_type?
  end

  def acceptable_image_size?
    return unless image.byte_size > 1.megabyte
    errors.add :image, "is over 1MB"
  end

  def acceptable_image_type?
    return if image.content_type.in? ["image/png", "image/jpeg"]
    errors.add :image, "must be a PNG or JPG"
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  include HasImage

  belongs_to :user

  has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :contact
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contacts
  has_many :events, through: :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_record

  private

  def invalid_record
    redirect_to "/404", alert: "Record not found"
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_records, only: [:show, :edit, :update, :destroy]

  def index
    @contacts = current_user.contacts
  end

  def show
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(build_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @contact.update(build_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully deleted.' }
    end
  end

  private

  def set_records
    @contact = current_user.contacts.find(params[:id])
  end

  def build_params
    default_params.merge(contact_params)
  end

  def default_params
    { user: current_user }
  end

  def contact_params
    params.fetch(:contact, {}).permit(:user_id, :name, :image, :company, :location, :email, :phone, :website, :twitter, :notes)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_contact
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = current_user.events
  end

  def show
  end

  def new
    @event = Event.new(contact: @contact)
  end

  def create
    @event = Event.new(build_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to [@event.contact, @event], notice: 'Event was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @event.update(build_params)
        format.html { redirect_to [@event.contact, @event], notice: 'Event was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully deleted.' }
    end
  end

  private

  def set_contact
    @contact = current_user.contacts.find(params[:contact_id])
  end

  def set_event
    @event = current_user.events.find(params[:id])
  end

  def build_params
    default_params.merge(event_params)
  end

  def default_params
    { contact_id: @contact.id }
  end

  def event_params
    params.fetch(:event, {}).permit(:contact_id, :title, :date, :notes)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def splash
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_form.html.erb
<%= render "layouts/error_explanation", object: contact %>

<%= form_with(model: contact, local: true) do |form| %>
  <div class="flex flex-wrap -mx-3 mb-6 max-w-2xl">
    <div class="w-full sm:w-1/2 px-3">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-field" %>
    </div>
    <div class="w-full sm:w-1/2 px-3">
      <%= form.label :image, class: "form-label" %>
      <%= form.file_field :image, class: "form-field" %>
    </div>
    <div class="w-full sm:w-1/2 px-3">
      <%= form.label :company, class: "form-label" %>
      <%= form.text_field :company, class: "form-field" %>
    </div>
    <div class="w-full sm:w-1/2 px-3">
      <%= form.label :location, class: "form-label" %>
      <%= form.text_field :location, class: "form-field" %>
    </div>
    <div class="w-full sm:w-1/2 px-3">
      <%= form.label :email, class: "form-label" %>
      <%= form.email_field :email, class: "form-field" %>
    </div>
    <div class="w-full sm:w-1/2 px-3">
      <%= form.label :phone, class: "form-label" %>
      <%= form.text_field :phone, class: "form-field" %>
    </div>
    <div class="w-full sm:w-1/2 px-3">
      <%= form.label :website, class: "form-label" %>
      <%= form.text_field :website, class: "form-field" %>
    </div>
    <div class="w-full sm:w-1/2 px-3">
      <%= form.label :twitter, class: "form-label" %>
      <%= form.text_field :twitter, class: "form-field" %>
    </div>
    <div class="w-full px-3">
      <%= form.label :notes, class: "form-label" %>
      <%= form.text_area :notes, class: "form-field" %>
    </div>
  </div>
  <%= form.submit "Submit", class: "btn" %>
<% end %>

app/views/contacts/_table_row.html.erb
<tr>
  <td>
    <%= link_to table_row.name, table_row %>
  </td>
  <td>
    <%= table_row.email %>
  </td>
  <td>
    <%= table_row.phone %>
  </td>
  <td>
    <%= link_to "Edit", [:edit, table_row], class: "btn bg-yellow-200" %>
    <%= link_to "Delete", table_row, method: :delete, class: "btn bg-red-200" %>
  </td>
</tr>

app/views/contacts/edit.html.erb
<div class="w-full pb-4">
  <h1 class="inline align-middle">
    Edit Contact
  </h1>
</div>

<%= render "form", contact: @contact %>

app/views/contacts/index.html.erb
<div class="w-full pb-4">
  <h1 class="inline align-middle">
    Contacts
  </h1>
  <%= link_to "Add New", [:new, :contact], class: "btn bg-blue-200 align-middle ml-4" %>
</div>
<div class="-my-2 py-2 overflow-x-auto">
  <div class="align-middle inline-block min-w-full shadow overflow-hidden sm:rounded-lg border-b border-gray-200">
    <table class="min-w-full">
      <thead>
        <tr>
          <th>
            Name
          </th>
          <th>
            Email
          </th>
          <th>
            Phone
          </th>
          <th>
            Actions
          </th>
        </tr>
      </thead>
      <tbody class="bg-white">
        <%= render partial: "table_row", collection: @contacts %>
      </tbody>
    </table>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="w-full pb-4">
  <h1 class="inline align-middle">
    New Contact
  </h1>
</div>

<%= render "form", contact: @contact %>

app/views/contacts/show.html.erb
<div class="w-full pb-4">
  <h1 class="inline align-middle">
    <%= @contact.name %>
  </h1>
  <%= link_to "Edit", [:edit, @contact], class: "btn bg-blue-200 align-middle ml-4" %>
</div>

<%= image_tag @contact.displayed_image, loading: "lazy", alt: @contact.name, class: "rounded-full" %>
<%= @contact.company %>
<%= @contact.location %>
<%= @contact.email %>
<%= @contact.phone %>
<%= @contact.twitter %>
<%= @contact.notes %>

<div class="w-full pb-4 pt-8">
  <h2 class="inline align-middle">
    Events
  </h2>
  <%= link_to "Add New", [:new, @contact, :event], class: "btn bg-blue-200 align-middle ml-4" %>
</div>

<div class="-my-2 py-2 overflow-x-auto">
  <div class="align-middle inline-block min-w-full shadow overflow-hidden sm:rounded-lg border-b border-gray-200">
    <table class="min-w-full">
      <thead>
        <tr>
          <th>
            Title
          </th>
          <th>
            Date
          </th>
          <th>
            Actions
          </th>
        </tr>
      </thead>
      <tbody class="bg-white">
        <%= render partial: "events/table_row", collection: @contact.events %>
      </tbody>
    </table>
  </div>
</div>

app/views/events/_form.html.erb
<%= render "layouts/error_explanation", object: event %>

<%= form_with(model: [@contact, event], local: true) do |form| %>
  <div class="flex flex-wrap -mx-3 mb-6 max-w-2xl">
    <div class="w-full sm:w-1/2 px-3">
      <%= form.label :title, class: "form-label" %>
      <%= form.text_field :title, class: "form-field" %>
    </div>
    <div class="w-full sm:w-1/2 px-3">
      <%= form.label :date, class: "form-label" %>
      <%= form.date_field :date, class: "form-field" %>
    </div>
    <div class="w-full px-3">
      <%= form.label :notes, class: "form-label" %>
      <%= form.text_area :notes, class: "form-field" %>
    </div>
  </div>
  <%= form.submit "Submit", class: "btn" %>
<% end %>

app/views/events/_table_row.html.erb
<tr>
  <td>
    <%= link_to table_row.title, [table_row.contact, table_row] %>
  </td>
  <td>
    <%= table_row.date %>
  </td>
  <td>
    <%= link_to "Edit", [:edit, table_row.contact, table_row], class: "btn bg-yellow-200" %>
    <%= link_to "Delete", [table_row.contact, table_row], method: :delete, class: "btn bg-red-200" %>
  </td>
</tr>

app/views/events/edit.html.erb
<div class="w-full pb-4">
  <h1 class="inline align-middle">
    Edit Event
  </h1>
</div>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<div class="w-full pb-4">
  <h1 class="inline align-middle">
    Events
  </h1>
  <%= link_to "Add New", [:new, :event], class: "btn bg-blue-200 align-middle ml-4" %>
</div>
<div class="-my-2 py-2 overflow-x-auto">
  <div class="align-middle inline-block min-w-full shadow overflow-hidden sm:rounded-lg border-b border-gray-200">
    <table class="min-w-full">
      <thead>
        <tr>
          <th>
            Title
          </th>
          <th>
            Date
          </th>
          <th>
            Actions
          </th>
        </tr>
      </thead>
      <tbody class="bg-white">
        <%= render partial: "table_row", collection: @events %>
      </tbody>
    </table>
  </div>
</div>

app/views/events/new.html.erb
<div class="w-full pb-4">
  <h1 class="inline align-middle">
    New Event
  </h1>
</div>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<%= @event.contact_id %>
<%= @event.title %>
<%= @event.date %>
<%= @event.notes %>

<%= link_to 'Edit', [:edit, @event.contact, @event] %>

app/views/layouts/_error_explanation.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(object.errors.count, "error") %> prohibited
      this form from being saved:
    </h2>
    <% object.errors.full_messages.each do |message| %>
      <div class="p-2 bg-red-800 items-center text-red-100 leading-none lg:rounded-full flex lg:inline-flex" role="alert">
        <span class="flex rounded-full bg-red-500 uppercase px-2 py-1 text-xs font-bold mr-3">
          <svg class="fill-current w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
            <path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/>
          </svg>
        </span>
        <span class="font-semibold mr-2 text-left flex-auto">
          <%= message %>
        </span>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<div class="pt-20">
  <header>
    <nav class="fixed top-0 flex w-full bg-white p-6">
      <div class="flex-1 text-gray-700">
        <%= link_to root_path do %>
          CRM
        <% end %>
      </div>

      <div class="flex-1 text-right">

        <% if user_signed_in? %>
          <%= link_to "Events", events_path, class: "menu-item" %>
          <%= link_to "Contacts", contacts_path, class: "menu-item" %>

          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "menu-item" %>
        <% else %>
          <%= link_to "Login", new_user_session_path, class: "menu-item" %>
          <%= link_to "Sign up", new_user_registration_path, class: "menu-item" %>
        <% end %>

      </div>
    </nav>
  </header>
</div>

app/views/layouts/_notice.html.erb
<% if notice %>
  <div class="text-center py-4 lg:px-4">
    <div class="p-2 bg-green-800 items-center text-green-100 leading-none lg:rounded-full flex lg:inline-flex" role="alert">
      <span class="flex rounded-full bg-green-500 uppercase px-2 py-1 text-xs font-bold mr-3">
        <svg class="fill-current w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
          <path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/>
        </svg>
      </span>
      <span class="font-semibold mr-2 text-left flex-auto">
        <%= notice %>
      </span>
    </div>
  </div>
<% end %>
<% if alert %>
  <div class="text-center py-4 lg:px-4">
    <div class="p-2 bg-red-800 items-center text-red-100 leading-none lg:rounded-full flex lg:inline-flex" role="alert">
      <span class="flex rounded-full bg-red-500 uppercase px-2 py-1 text-xs font-bold mr-3">
        <svg class="fill-current w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
          <path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/>
        </svg>
      </span>
      <span class="font-semibold mr-2 text-left flex-auto">
        <%= alert %>
      </span>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRM</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/notice" %>
    <div class="flex flex-wrap px-6">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/splash.html.erb
Splash page